/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onegold_maskchecker_MainActivity */

#ifndef _Included_com_onegold_maskchecker_MainActivity
#define _Included_com_onegold_maskchecker_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onegold_maskchecker_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_onegold_maskchecker_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
